# Generated by Django 3.0.5 on 2020-04-29 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=30, unique=True, verbose_name='Rut')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
            ],
            options={
                'db_table': 'employee',
                'ordering': ['rut'],
            },
        ),
    ]
